server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: accountRoutes
          uri: http://localhost:8080
          predicates:
           - Path=/account/**
        - id: usuarioRoute
          uri: lb://API-USUARIO
          predicates:
           - Path=/usuario/**
        - id: contaRoute
          uri: lb://API-CONTA
          predicates:
           - Path=/conta/**
          filters:
            - AddRequestHeader=user-request-header, custom-user-request-header
            - AddResponseHeader=user-response-header, custom-user-response-header 